name: ${project.name}
version: ${project.version}
description: The ${project.name} plugin allows users to easily vote for actions taken by other users.
main: ${main.class}
database: true
commands:
  up:
    permission: vota.vote
    usage: "Usage: /up (Name) [Time]"
    description: "Votes a user up"
  down:
    permission: vota.vote
    usage: "Usage: /down (Name) [Time]"
    description: "Votes a user down"
permissions:
  vota.approve:
    description: "Allows you to approve a vote"
  vota.vote:
    description: "Allows you to vote other users"
