name: ${project.name}
version: ${project.version}
description: The ${project.name} plugin allows users to easily vote for actions taken by other users.
main: ${main.class}
database: true
commands:
  up:
    permission: vota.vote
    usage: "Usage: /up (Name) [Time]"
    description: "Votes a user up"
  down:
    permission: vota.vote
    usage: "Usage: /down (Name) [Time]"
    description: "Votes a user down"
  top10:
    permission: vota.stats
    usage: "Usage: /top10"
    description: "Shows the top 10 of voted users"
  stats:
    permission: vota.stats
    usage: "Usage: /stats [Name]"
    description: "Shows the currents marks for the given user or for the command sender if no name is given"
permissions:
  vota.approve:
    description: "Allows you to approve a vote"
  vota.vote:
    description: "Allows you to vote other users"
  vota.stats:
    description: "Allows you to display the top 10 list of voted users"
